project_name: eetgateway

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go fmt ./...

builds:
  - main: ./cmd/eetgateway
    binary: eetg
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X github.com/chutommy/eetgateway/pkg/cmd.eetgOS={{.Os}}
               -X github.com/chutommy/eetgateway/pkg/cmd.eetgArch={{.Arch}}
               -X github.com/chutommy/eetgateway/pkg/cmd.eetgVersion={{.Version}}
               -X github.com/chutommy/eetgateway/pkg/cmd.eetgBuildTime={{.Date}}"

archives:
  - wrap_in_directory: true
    files:
      - LICENSE
      - docs/*

# TODO: add packages for package managers
# https://goreleaser.com/customization/nfpm/
# https://goreleaser.com/customization/snapcraft/
# https://goreleaser.com/customization/docker/
# https://goreleaser.com/customization/docker_manifest/
# https://goreleaser.com/customization/homebrew/

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

changelog:
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^style'
      - '^chore'
      - '^test'
      - '^ci'
      - 'typo'

release:
  draft: false
  discussion_category_name: General

  name_template: "EETGateway v{{.Version}}"

  header: |
    ### Release date {{ .Date }}

    Welcome to this new release!

  footer: |
    ### Thanks!

    Those were the changes on {{ .Tag }}!

source:
  enabled: true

milestones:
  - close: true
    fail_on_error: false
    name_template: "{{ .Tag }}"

snapshot:
  name_template: "{{ incpatch .Version }}-SNAPSHOT-{{.ShortCommit}}"