basePath: /v1
consumes:
- application/json
definitions:
  PingResponse:
    properties:
      eet_gateway:
        example: online
        type: string
      keystore:
        example: online
        type: string
      tax_admin:
        example: online
        type: string
    type: object
  httphandler.GatewayErrResp:
    properties:
      gateway_error:
        type: string
    type: object
  httphandler.StoreCertReq:
    properties:
      cert_id:
        type: string
      cert_password:
        type: string
      pkcs12_data:
        items:
          type: integer
        type: array
      pkcs12_password:
        type: string
    required:
    - cert_id
    - pkcs12_data
    - pkcs12_password
    type: object
  httphandler.SuccessCertResp:
    properties:
      cert_id:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: pro@chutommy.com
    name: Tommy Chu
  description: Specifikace REST API služby EET Gateway.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: EET Gateway API
  version: "1.0"
paths:
  /certs:
    post:
      consumes:
      - application/json
      description: Nahraje certifikát do služby keystore a umožní příslušnému daňovému
        poplatníkovi odesílat e-tržby v systému EET Gateway.
      operationId: storeCert
      parameters:
      - description: Dotaz na nahrání certifikátu daňového poplatníka.
        in: body
        name: cert_id
        required: true
        schema:
          allOf:
          - $ref: '#/definitions/httphandler.StoreCertReq'
          - properties:
              pkcs12data:
                type: string
            type: object
      produces:
      - application/json
      responses:
        "200":
          description: Dotaz byl úspěšně zpracovaný.
          schema:
            $ref: '#/definitions/httphandler.SuccessCertResp'
        "400":
          description: Tělo požadavku je neplatný (chyba ve struktuře, datovém typu,
            ...).
          schema:
            $ref: '#/definitions/httphandler.GatewayErrResp'
      summary: Nahrát certifikát daňového poplatníka
      tags:
      - Certifikáty
  /ping:
    get:
      description: Ověří stav API služby EET Gateway, keystore (službu spravující
        databázi) a spojení se servery správce daně.
      operationId: ping
      produces:
      - application/json
      responses:
        "200":
          description: Všechny EETG komponenty jsou dostupné.
          schema:
            $ref: '#/definitions/PingResponse'
        "503":
          description: Některé EETG komponeny jsou nedostupné.
          schema:
            $ref: '#/definitions/PingResponse'
      summary: Ověřit stav EETG API
      tags:
      - API
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
