basePath: /v1
consumes:
- application/json
definitions:
  GatewayErrorResponse:
    properties:
      gateway_error:
        example: keystore service unavailable
        type: string
    type: object
  PingResponse:
    properties:
      eet_gateway:
        example: online
        type: string
      keystore:
        example: online
        type: string
      tax_admin:
        example: online
        type: string
    type: object
  StoreCertificateRequest:
    properties:
      cert_id:
        example: d406ccda-1bc5-44ab-a081-af6e8740634c
        type: string
      cert_password:
        example: 10f47cc7eb3c51
        type: string
      pkcs12_data:
        example: MIIPoq7Huhj ... HXJBdPA=
        format: base64
        type: string
      pkcs12_password:
        example: "1234"
        type: string
    required:
    - cert_id
    - cert_password
    - pkcs12_data
    - pkcs12_password
    type: object
  SuccessResponse:
    properties:
      cert_id:
        example: d406ccda-1bc5-44ab-a081-af6e8740634c
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: pro@chutommy.com
    name: Tommy Chu
  description: Specifikace REST API služby EET Gateway.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: EET Gateway API
  version: "1.0"
paths:
  /certs:
    post:
      consumes:
      - application/json
      description: Nahraje certifikát do služby keystore a umožní příslušnému daňovému
        poplatníkovi odesílat e-tržby v systému EET Gateway.
      operationId: storeCert
      parameters:
      - description: Tělo požadavku na nahrání certifikátu.
        in: body
        name: cert_id
        required: true
        schema:
          $ref: '#/definitions/StoreCertificateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Dotaz byl úspěšně zpracovaný.
          schema:
            $ref: '#/definitions/SuccessResponse'
        "400":
          description: Vložený certifikát daňového poplatníka je neplatný.
          schema:
            $ref: '#/definitions/GatewayErrorResponse'
        "409":
          description: ID certifikátu je již zabraný. Konfliktní certifikát musí být
            odstraněn nebo pro tento zvoleno jiné ID.
          schema:
            $ref: '#/definitions/GatewayErrorResponse'
        "500":
          description: Naskytla se neočekávaná chyba databáze.
          schema:
            $ref: '#/definitions/GatewayErrorResponse'
        "503":
          description: Služba keystore je nedostupná.
          schema:
            $ref: '#/definitions/GatewayErrorResponse'
      summary: Nahrát certifikát daňového poplatníka
      tags:
      - Certifikáty
  /ping:
    get:
      description: Ověří stav API služby EET Gateway, keystore (službu spravující
        databázi) a spojení se servery správce daně.
      operationId: ping
      produces:
      - application/json
      responses:
        "200":
          description: Všechny EETG komponenty jsou dostupné.
          schema:
            $ref: '#/definitions/PingResponse'
        "503":
          description: Některé EETG komponeny jsou nedostupné.
          schema:
            $ref: '#/definitions/PingResponse'
      summary: Ověřit stav EETG API
      tags:
      - API
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
