// Code generated by mockery v2.9.4. DO NOT EDIT.

// EETGateway - Tommy Chu

package mocks

import (
	context "context"

	keystore "github.com/chutommy/eetgateway/pkg/keystore"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Service) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id, password
func (_m *Service) Get(ctx context.Context, id string, password []byte) (*keystore.KeyPair, error) {
	ret := _m.Called(ctx, id, password)

	var r0 *keystore.KeyPair
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) *keystore.KeyPair); ok {
		r0 = rf(ctx, id, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keystore.KeyPair)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, id, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *Service) List(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ping provides a mock function with given fields: ctx
func (_m *Service) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store provides a mock function with given fields: ctx, id, password, kp
func (_m *Service) Store(ctx context.Context, id string, password []byte, kp *keystore.KeyPair) error {
	ret := _m.Called(ctx, id, password, kp)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, *keystore.KeyPair) error); ok {
		r0 = rf(ctx, id, password, kp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateID provides a mock function with given fields: ctx, oldID, newID
func (_m *Service) UpdateID(ctx context.Context, oldID string, newID string) error {
	ret := _m.Called(ctx, oldID, newID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, oldID, newID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePassword provides a mock function with given fields: ctx, id, oldPassword, newPassword
func (_m *Service) UpdatePassword(ctx context.Context, id string, oldPassword []byte, newPassword []byte) error {
	ret := _m.Called(ctx, id, oldPassword, newPassword)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, []byte) error); ok {
		r0 = rf(ctx, id, oldPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
